#### 1. Import the numpy package under the name `np` (★☆☆)
`hint: import … as`

In [2]:
import numpy as np

#### 2. Create a null vector of size 10 (★☆☆)

In [5]:
np.zeros(10)


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 3. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
five_vector = np.zeros(10)
five_vector [4] = 1


#### 4. Create a vector with values ranging from 10 to 49 (★☆☆)
`hint: arange`

In [8]:
np.arange(10, 50)

#### 5. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)
`hint: reshape`

In [11]:
np.arange(0,9).reshape((3, 3))

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 6. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)
`hint: np.nonzero`

In [12]:
np.nonzero([1,2,0,0,4,0])

(array([0, 1, 4], dtype=int64),)

#### 7. Create a 3x3 identity matrix (★☆☆)
`hint: np.eye`

In [ ]:
# A what now?
np.eye(3, k=1)

#### 8. Create a 3x3x3 array with random values (★☆☆)
`hint: np.random.random`

In [14]:
np.random.seed(1000) #?
np.random.random((3,3,3))


array([[[0.65358959, 0.11500694, 0.95028286],
        [0.4821914 , 0.87247454, 0.21233268],
        [0.04070962, 0.39719446, 0.2331322 ]],

       [[0.84174072, 0.20708234, 0.74246953],
        [0.39215413, 0.18225652, 0.74353941],
        [0.06958208, 0.8853372 , 0.9526444 ]],

       [[0.93114343, 0.41543095, 0.02898166],
        [0.98202748, 0.33963768, 0.70668719],
        [0.36187707, 0.0351059 , 0.85505825]]])

#### 9. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)
`hint: min, max`

In [16]:
remember_me = np.random.random((3,3,3))
print(str(remember_me))
print(str(remember_me.min()))
print(str(remember_me.max()))

[[[0.5196043  0.56598883 0.44116739]
  [0.13755616 0.21354319 0.13337189]
  [0.3222967  0.23388712 0.52749816]]

 [[0.56597116 0.43822528 0.32187262]
  [0.55964081 0.86534558 0.84728288]
  [0.10781717 0.31631948 0.40947866]]

 [[0.68708901 0.70223529 0.44619794]
  [0.42032208 0.80263059 0.53861757]
  [0.92350049 0.06190754 0.36758345]]]
0.061907537224691445
0.9235004894140457


#### 10. Create a random vector of size 30 and find the mean value (★☆☆)
`hint: mean`

In [18]:
remember_me = np.random.random((30))
print(str(remember_me))
remember_me.mean() 

[0.48258449 0.47647761 0.44603283 0.81607006 0.27435149 0.06196201
 0.96029634 0.45811813 0.75789206 0.6811586  0.54177793 0.13283249
 0.25320563 0.44385559 0.55874991 0.81386435 0.31782834 0.39704509
 0.89016825 0.82541621 0.10668708 0.15977588 0.65121931 0.56906421
 0.98408367 0.74915901 0.80239963 0.22830988 0.51871345 0.6301084 ]


0.53297359842906

#### 11. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
`hint: np.diag`

In [37]:
# that was a curveball
fiver_matrix = np.diagflat([1,2,3,4], -1)
print(str(fiver_matrix))


[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 12. Normalize a 5x5 random matrix (★☆☆)
`hint: (x -mean)/std`

In [44]:
remember_me = np.random.random((5,5))
my_mean = remember_me.mean()
my_standard_deviation = remember_me.std()
with np.nditer(remember_me, op_flags=['readwrite']) as iterate_through_me:
    for normalized_value in iterate_through_me:
        normalized_value = (normalized_value-my_mean ) / my_standard_deviation 
print(str(remember_me ))

[[0.98114044 0.89662233 0.53319582 0.03514239 0.83771878]
 [0.90390791 0.63034084 0.28100079 0.93270378 0.01791405]
 [0.32063769 0.35118622 0.84920097 0.0043367  0.64806747]
 [0.55551553 0.33740075 0.08523243 0.14664603 0.65784615]
 [0.04582828 0.06191159 0.45783951 0.52105861 0.01555496]]


#### 13. How to find common values between two arrays? (★☆☆)
`hint: np.intersect1d`

In [42]:
np.intersect1d([1, 3, 4, 3], [3, 1, 2, 1])

array([1, 3])

#### 14. Create a random vector of size 10 and sort it (★★☆)
`hint: sort`

In [47]:
print(str(np.sort(np.random.random((10)))))

[0.12123591 0.14461898 0.27283478 0.38831108 0.45639316 0.66949207
 0.74230176 0.77995504 0.98216764 0.98839328]


#### 15. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
`hint: argmax`

In [51]:
remember_me = np.random.random((10))
print(str(remember_me))
remember_me[np.argmax(remember_me)] = 0
remember_me


[0.49714374 0.91632645 0.12732982 0.50794403 0.07031555 0.63187394
 0.24285126 0.13779269 0.24031744 0.36967976]
[0.49714374 0.         0.12732982 0.50794403 0.07031555 0.63187394
 0.24285126 0.13779269 0.24031744 0.36967976]


#### 16. Subtract the mean of each row of a matrix (★★☆)
`hint: mean(axis=,keepdims=)`

In [76]:
remember_me = np.random.random((5,5))
print(str(remember_me))
my_number_of_colums = remember_me.shape[0]
my_number_of_rows= remember_me.shape[1]
my_means = np.mean(remember_me , axis=1, keepdims = True)

for i in range(0,my_number_of_rows):
    rows_mean = my_means[i]
    for j in range(0,my_number_of_colums):
        remember_me[j,i] = remember_me[j,i]-rows_mean

print(remember_me)

[[0.95085504 0.01700526 0.1606255  0.13630294 0.84578035]
 [0.68887179 0.65619176 0.79591354 0.19598444 0.81593675]
 [0.31732619 0.03853339 0.45136664 0.83896988 0.09555471]
 [0.76593594 0.13538339 0.78966134 0.27841027 0.80856534]
 [0.15440397 0.73016279 0.0194405  0.84345707 0.55173149]]
[[ 0.52874122 -0.61357439 -0.18772466 -0.41928831  0.38594119]
 [ 0.26675797  0.0256121   0.44756338 -0.35960682  0.35609759]
 [-0.10478763 -0.59204626  0.10301648  0.28337863 -0.36428446]
 [ 0.34382212 -0.49519626  0.44131118 -0.27718099  0.34872618]
 [-0.26770985  0.09958313 -0.32890966  0.28786581  0.09189232]]


#### 17. How to get the n largest values of an array (★★★)
`Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
hint: np.argsort | np.argpartition`

In [73]:
Z = np.arange(10000)
np.random.shuffle(Z)
n=5
sorted_indizies = np.argsort(Z).tolist()
sorted_indizies.reverse()
for indizie_index in range(0,n):
    print(Z[sorted_indizies[indizie_index ]])


9999
9998
9997
9996
9995


#### 18. Create a random 5*3 matrix and replace items that are larger than 4 by their squares ( Example:  6 --> 36) 
`hint: np.where`

In [110]:
remember_me = np.random.random((5,3))
remember_me = np.multiply(remember_me,10) # otherwise the where doesn't find anything

remember_me_different = np.reshape(remember_me,15)
print(str(remember_me))
remember_me = np.where(remember_me_different < 4.0, remember_me_different, remember_me_different*remember_me_different)
remember_me  = remember_me.reshape(5,3)
remember_me

[[4.10570677 5.79684124 3.38262835]
 [9.27065821 4.74792803 8.98202613]
 [1.4938061  1.34901437 6.15367126]
 [3.99384453 3.42950329 2.0285625 ]
 [5.513233   6.75928724 5.21556072]]


array([[16.8568281 , 33.60336838,  3.38262835],
       [85.9451037 , 22.54282057, 80.67679344],
       [ 1.4938061 ,  1.34901437, 37.86766995],
       [ 3.99384453,  3.42950329,  2.0285625 ],
       [30.39573809, 45.68796393, 27.2020736 ]])